### ISSUE TITLE
dependency conflicts scipy and stochastic

### ISSUE THREAD

**Issue by kmezhoud** [wissem01chiha/alpr#1]
Hi, 
Thank you for this package.
In the end of  installation I got this Error message
```{python}
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
stochastic 0.7.0 requires scipy<2.0,>=1.8, but you have scipy 1.6.0 which is incompatible.
```
The installation is well done (second installation)

```
site-packages is not writeable
Processing ./dist/cil4sys-0.1.tar.gz
  Preparing metadata (setup.py) ... done
Requirement already satisfied: multiprocess==0.70.15 in /home/kirus/.local/lib/python3.10/site-packages (from cil4sys==0.1) (0.70.15)
Requirement already satisfied: numpy==1.23.5 in /home/kirus/.local/lib/python3.10/site-packages (from cil4sys==0.1) (1.23.5)
Requirement already satisfied: opencv_python==4.5.5.62 in /home/kirus/.local/lib/python3.10/site-packages (from cil4sys==0.1) (4.5.5.62)
Requirement already satisfied: Pillow==10.0.0 in /home/kirus/.local/lib/python3.10/site-packages (from cil4sys==0.1) (10.0.0)
Requirement already satisfied: pytesseract==0.3.10 in /home/kirus/.local/lib/python3.10/site-packages (from cil4sys==0.1) (0.3.10)
Requirement already satisfied: scipy==1.6.0 in /home/kirus/.local/lib/python3.10/site-packages (from cil4sys==0.1) (1.6.0)
Requirement already satisfied: setuptools==68.1.2 in /home/kirus/.local/lib/python3.10/site-packages (from cil4sys==0.1) (68.1.2)
Requirement already satisfied: scikit-image==0.18.1 in /home/kirus/.local/lib/python3.10/site-packages (from cil4sys==0.1) (0.18.1)
Requirement already satisfied: dill>=0.3.7 in /home/kirus/.local/lib/python3.10/site-packages (from multiprocess==0.70.15->cil4sys==0.1) (0.3.7)
Requirement already satisfied: packaging>=21.3 in /home/kirus/.local/lib/python3.10/site-packages (from pytesseract==0.3.10->cil4sys==0.1) (23.2)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in /home/kirus/.local/lib/python3.10/site-packages (from scikit-image==0.18.1->cil4sys==0.1) (3.8.0)
Requirement already satisfied: networkx>=2.0 in /home/kirus/.local/lib/python3.10/site-packages (from scikit-image==0.18.1->cil4sys==0.1) (3.2.1)
Requirement already satisfied: imageio>=2.3.0 in /home/kirus/.local/lib/python3.10/site-packages (from scikit-image==0.18.1->cil4sys==0.1) (2.33.0)
Requirement already satisfied: tifffile>=2019.7.26 in /home/kirus/.local/lib/python3.10/site-packages (from scikit-image==0.18.1->cil4sys==0.1) (2023.9.26)
Requirement already satisfied: PyWavelets>=1.1.1 in /home/kirus/.local/lib/python3.10/site-packages (from scikit-image==0.18.1->cil4sys==0.1) (1.5.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/kirus/.local/lib/python3.10/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image==0.18.1->cil4sys==0.1) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /home/kirus/.local/lib/python3.10/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image==0.18.1->cil4sys==0.1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/kirus/.local/lib/python3.10/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image==0.18.1->cil4sys==0.1) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/kirus/.local/lib/python3.10/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image==0.18.1->cil4sys==0.1) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image==0.18.1->cil4sys==0.1) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in /home/kirus/.local/lib/python3.10/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image==0.18.1->cil4sys==0.1) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib!=3.0.0,>=2.0.0->scikit-image==0.18.1->cil4sys==0.1) (1.16.0)
Building wheels for collected packages: cil4sys
  Building wheel for cil4sys (setup.py) ... done
  Created wheel for cil4sys: filename=cil4sys-0.1-py3-none-any.whl size=17985676 sha256=451df7ca4c975f6100e09f74ba811d141faa3d32deffd279c1290217194d3133
  Stored in directory: /home/kirus/.cache/pip/wheels/94/c5/9b/8e49563ac201c4a1a3daaa6a738063425fe2865d1b859fd60a
Successfully built cil4sys
Installing collected packages: cil4sys
  Attempting uninstall: cil4sys
    Found existing installation: cil4sys 0.1
    Uninstalling cil4sys-0.1:
      Successfully uninstalled cil4sys-0.1
Successfully installed cil4sys-0.1
```
BUT
When I run ``` python3 main.py ```

I got  error during importing packages

```
python3 main.py 
Traceback (most recent call last):
  File "/media/DATA/ComputerVision/cil4sys/main.py", line 44, in <module>
    from        skimage import  filters
  File "/home/kirus/.local/lib/python3.10/site-packages/skimage/filters/__init__.py", line 4, in <module>
    from .edges import (sobel, sobel_h, sobel_v,
  File "/home/kirus/.local/lib/python3.10/site-packages/skimage/filters/edges.py", line 18, in <module>
    from ..restoration.uft import laplacian
  File "/home/kirus/.local/lib/python3.10/site-packages/skimage/restoration/__init__.py", line 5, in <module>
    from .deconvolution import wiener, unsupervised_wiener, richardson_lucy
  File "/home/kirus/.local/lib/python3.10/site-packages/skimage/restoration/deconvolution.py", line 6, in <module>
    from scipy.signal import convolve
  File "/home/kirus/.local/lib/python3.10/site-packages/scipy/signal/__init__.py", line 302, in <module>
    from .filter_design import *
  File "/home/kirus/.local/lib/python3.10/site-packages/scipy/signal/filter_design.py", line 16, in <module>
    from scipy import special, optimize, fft as sp_fft
  File "/home/kirus/.local/lib/python3.10/site-packages/scipy/optimize/__init__.py", line 421, in <module>
    from ._shgo import shgo
  File "/home/kirus/.local/lib/python3.10/site-packages/scipy/optimize/_shgo.py", line 9, in <module>
    from scipy import spatial
  File "/home/kirus/.local/lib/python3.10/site-packages/scipy/spatial/__init__.py", line 107, in <module>
    from . import distance, transform
  File "/home/kirus/.local/lib/python3.10/site-packages/scipy/spatial/transform/__init__.py", line 19, in <module>
    from .rotation import Rotation, Slerp
ImportError: /home/kirus/.local/lib/python3.10/site-packages/scipy/spatial/transform/rotation.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send

```
After updating  ```scipy``` with ```pip install scipy==1.8.1``` , The package seems to work well with the default video.mp4.

```
python3 main.py 
[INFO] Configuring Environment ...
[INFO] Reading Variable Files ...
[INFO] Starting Video Processing
[INFO] Capturing video ...
[SUCESS] video captured in 0 seconds
[INFO] Generating Frames ...
[SUCESS] 181 frames generated in 7 seconds
[INFO] Preprocessing Frames ...
[SUCESS] frames preprocessed in 17 seconds
[INFO] Filtring and Denoisng Frames ...
[SUCESS] frames filtred and denoised in 19 seconds
[INFO] frames sorted in 19 seconds
[INFO] Numerical Character Detection ... 

````
and during this `/data/images/video_frames` and `/data/images/roi_frames`  folders were generated.

**Maybe it is necessary to update ```setup.py``` with ```scipy==1.8.1```**

But after I got this error

```
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:19
Traceback (most recent call last):
  File "/home/kirus/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 255, in run_tesseract
    proc = subprocess.Popen(cmd_args, **subprocess_args())
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tesseract'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/DATA/ComputerVision/cil4sys/main.py", line 347, in <module>
    chars = pytesseract.image_to_string(img_result, lang='eng')
  File "/home/kirus/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 423, in image_to_string
    return {
  File "/home/kirus/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/kirus/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 288, in run_and_get_output
    run_tesseract(**kwargs)
  File "/home/kirus/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 260, in run_tesseract
    raise TesseractNotFoundError()
pytesseract.pytesseract.TesseractNotFoundError: tesseract is not installed or it's not in your PATH. See README file for more information.

```

**How we an setup inputs like  live camera or recorded video?**

Note:
I am on PC without camera (ubuntu). And I just want to use camera recorded video as INPUT.

Many Thanks,
Karim

**Comment by kmezhoud** [comment]
```
pip3 list | grep tesseract
pytesseract               0.3.10
tesseract                 0.1.3

```

**Comment by kmezhoud** [comment]
Possible cause of this error (about tesseract) is that I installed ```pytesseract``` with ```pip``` without installing the binary. If that is the case, you can install it as following [source](https://stackoverflow.com/questions/68084044/error-tesseract-is-not-installed-or-its-not-in-your-path):
```
sudo apt update
sudo apt install tesseract-ocr
sudo apt install libtesseract-dev
```
And now it is better:

```
python3 main.py 
[INFO] Configuring Environment ...
[INFO] Reading Variable Files ...
[INFO] Starting Video Processing
[INFO] Capturing video ...
[SUCESS] video captured in 0 seconds
[INFO] Generating Frames ...
[SUCESS] 181 frames generated in 7 seconds
[INFO] Preprocessing Frames ...
[SUCESS] frames preprocessed in 19 seconds
[INFO] Filtring and Denoisng Frames ...
[SUCESS] frames filtred and denoised in 20 seconds
[INFO] frames sorted in 21 seconds
[INFO] Numerical Character Detection ... 
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:21
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:21
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:225-0
[INFO] Time Remaining:21
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:22
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:22
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:22
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:22
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:22
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:22
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:22
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:22
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:22
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-7526
[INFO] Time Remaining:23
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:23
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:23
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:24
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:24
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:24
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:79
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:80
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:80
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:80
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:81
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:82
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:82
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:82
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:82
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:82
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:82
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:82
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:82
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:82
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:82
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:83
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:83
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:83
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:83
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:83
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:83
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:84
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:89
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:89
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:89
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:89
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:89
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:94
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:100
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:100
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:100
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:100
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:102
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:102
---------------------------------------------
[FAIL] licence plate not detected ! 
[INFO] processing possible best matched numbers ...
[INFO] car number is:0-0
[INFO] Time Remaining:103
[INFO] end program !

```
But the plate is not detected.
Any Idea is welcome.
Thanks!

**Comment by wissem01chiha** [comment]
Dear  **kmezhoud**;

Thanks very much for you interest in my project. I am so grateful  for your remakes. 

First I developed the software on Windows 11 and USB Cam video  camera witch  run on **python 3.11.4** , then i used to compile it to Raspberry pi 3B+ witch run on Raspbian OS , so there was many libs had incompatibility issues , for the Raspbian **(Default python 3.9)**, i make some changes to make it works ( lib version listed in **setup.py** might not  work under any laptop )
 so 
try to downgrade your python version and rerun.

Second , the last output  ( program exist without plate detection) is due the tesseract  engine version , with some versions it do not  work well. try to change the version or use another better OCR engine or
 it's due to the matching character function **matching_number.py** go to line 355 to 370  of the **main.py** code : 

 ```
 serie_detected,reg_detected,s,reg=utils.matching_number(plate_chars)
    if(serie_detected and reg_detected):
        print("---------------------------------------------")
        print("[SUCESS] licence plate detected succesfully :")
        print("[INFO] car number is:%d-%d"%(reg,s))
        t=time.time()-start_time
        print("[INFO] Time Remaining:%d"% t )  
        print("[INFO] Exit Process!")
        break
    else:
        print("---------------------------------------------")
        print("[FAIL] licence plate not detected ! ")
        print("[INFO] processing possible best matched numbers ...")
        print("[INFO] car number is:%d-%d"%(reg,s))
        t=time.time()-start_time
        print("[INFO] Time Remaining:%d"%  t)
```

and replace it with : 
 ```
serie_detected,reg_detected,s,reg=utils.matching_number(plate_chars)
 print("---------------------------------------------")
 print("[SUCESS] licence plate detected succesfully :")
 print("[INFO] car number is:%d-%d"%(reg,s))
 t=time.time()-start_time
 print("[INFO] Time Remaining:%d"% t )  
 print("[INFO] Exit Process!")
```
        

you  should print many character including numbers , symbols , .... and show me the result. 

the function **matching_number.py**  should be implemented with a fuzzy logic or probabilistic approach , hence in the project we don t find time to implement that.   



For video recording , there was a function implemented **capture_video.py**   in video module. it works for the default hardware camera (it works fine for the Raspberry pi camera, check it for  laptop camera records )


The actual version use recognition from proceed images one by one , the cod do not  make correlation between results extracted from previous image , try to implement a **feature localization** module and a comparison process.

**Comment by wissem01chiha** [comment]
Thanks very much Dr Karim for you advices , I will correct the dependency issue with the release of a docker image soon  , and i will improve the detection functionally in order to get more accurate results.
I am happy to invite you to fork the repo and contribute to the project Dr. It's a great pleasure.

**Comment by Stan92** [comment]
Hi Wissem
Could you please tell me what you've done under windows?
I'm trying to run the project but it fails while installing the packages
I use Python 3.11 and I get some errors with these packages (from your requirements.txt)
scipy==1.8.1
setuptools==68.1.2
setuptools==65.5.0
skimage==0.0
Btw, I m very new to python

**Comment by wissem01chiha** [comment]
Hi, @Stan92, thank you very much for your comment! The package was developed using Python version 3.11.4, which matches your version. I noticed that the issue you're experiencing is likely caused by dependency conflicts within your Python libraries, such as NumPy, SciPy, and others. Here's what I recommend:
Copy and paste the errors you encountered during installation, along with the commands you ran, so I can help identify the conflicts.
- Update your Python package manager (e.g., pip or conda) with the following commands:
for pip:
`python -m pip install --upgrade pip`
 for Anaconda:
 `conda update conda`
 `conda update --all`
- Try installing the dependencies listed in the requirements.txt file using your package manager (pip or conda) without specifying versions. You can modify the requirements.txt by removing version numbers and then re-run the command.
- recommended solution (which is  more advanced): Work with a virtual environment. The issue might be caused by library versions installed globally on your machine. create a virtual environment in your workspace and install the specific versions from requirements.txt can help. More details on how to do this can be found here: [Python Virtual Environments](https://www.dataquest.io/blog/a-complete-guide-to-python-virtual-environments/).

If the error still persists, please open a new issue, including the title of the libraries causing the problem, or reach me at: chihawissem08@gmail.com.

- please mention if you are building the package for an other platform than windows e.g. 'Linux', or 'macOS', or any embedded development board, thanks!
